import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as bcrypt from 'bcrypt';
import { createCipheriv, createDecipheriv, randomBytes } from 'crypto';

const ENCRYPTION_ALGORITHM = 'aes-256-gcm';
const ENCRYPTION_IV_LENGTH = 16;
const ENCRYPTION_AUTH_TAG_LENGTH = 16;

/**
 * Handles token encryption/decryption and secure hashing helpers.
 */
@Injectable()
export class EncryptionService {
  private readonly encryptionKey: Buffer;

  public constructor(private readonly configService: ConfigService) {
    const encryptionKeyHex = this.configService.getOrThrow<string>('ENCRYPTION_KEY');
    const key = Buffer.from(encryptionKeyHex, 'hex');

    if (key.length !== 32) {
      throw new Error('ENCRYPTION_KEY must be a 64-char hex string (32 bytes)');
    }

    this.encryptionKey = key;
  }

  /**
   * Encrypts plaintext with AES-256-GCM.
   */
  public encrypt(plaintext: string): string {
    const iv = randomBytes(ENCRYPTION_IV_LENGTH);
    const cipher = createCipheriv(ENCRYPTION_ALGORITHM, this.encryptionKey, iv);
    const encrypted = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
    const authTag = cipher.getAuthTag();

    return `${iv.toString('hex')}:${authTag.toString('hex')}:${encrypted.toString('hex')}`;
  }

  /**
   * Decrypts ciphertext generated by `encrypt`.
   */
  public decrypt(encryptedPayload: string): string {
    const [ivHex, authTagHex, cipherHex] = encryptedPayload.split(':');

    if (!ivHex || !authTagHex || !cipherHex) {
      throw new Error('Invalid encrypted payload format');
    }

    const iv = Buffer.from(ivHex, 'hex');
    const authTag = Buffer.from(authTagHex, 'hex');
    const ciphertext = Buffer.from(cipherHex, 'hex');

    if (iv.length !== ENCRYPTION_IV_LENGTH) {
      throw new Error('Invalid IV length');
    }

    if (authTag.length !== ENCRYPTION_AUTH_TAG_LENGTH) {
      throw new Error('Invalid auth tag length');
    }

    const decipher = createDecipheriv(ENCRYPTION_ALGORITHM, this.encryptionKey, iv);
    decipher.setAuthTag(authTag);
    const decrypted = Buffer.concat([decipher.update(ciphertext), decipher.final()]);

    return decrypted.toString('utf8');
  }

  /**
   * Hashes a value with bcrypt.
   */
  public async hash(value: string): Promise<string> {
    return bcrypt.hash(value, 10);
  }

  /**
   * Compares plaintext and hash values with bcrypt.
   */
  public async compare(value: string, hash: string): Promise<boolean> {
    return bcrypt.compare(value, hash);
  }
}
