/**
 * Application-level error codes used in API responses and client handling.
 */
export const ErrorCodes = {
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_GITHUB_FAILED: 'AUTH_GITHUB_FAILED',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',

  DO_ACCOUNT_NOT_FOUND: 'DO_ACCOUNT_NOT_FOUND',
  DO_ACCOUNT_INVALID_TOKEN: 'DO_ACCOUNT_INVALID_TOKEN',
  DO_ACCOUNT_VALIDATION_FAILED: 'DO_ACCOUNT_VALIDATION_FAILED',
  DO_ACCOUNT_INSUFFICIENT_PERMISSIONS: 'DO_ACCOUNT_INSUFFICIENT_PERMISSIONS',

  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_NAME_TAKEN: 'PROJECT_NAME_TAKEN',
  PROJECT_FORBIDDEN: 'PROJECT_FORBIDDEN',

  ENVIRONMENT_NOT_FOUND: 'ENVIRONMENT_NOT_FOUND',
  ENVIRONMENT_NAME_TAKEN: 'ENVIRONMENT_NAME_TAKEN',

  REPOSITORY_NOT_FOUND: 'REPOSITORY_NOT_FOUND',
  REPOSITORY_ALREADY_CONNECTED: 'REPOSITORY_ALREADY_CONNECTED',
  REPOSITORY_ACCESS_DENIED: 'REPOSITORY_ACCESS_DENIED',
  REPOSITORY_WEBHOOK_CREATION_FAILED: 'REPOSITORY_WEBHOOK_CREATION_FAILED',

  CONFIG_INVALID_YAML: 'CONFIG_INVALID_YAML',
  CONFIG_VALIDATION_FAILED: 'CONFIG_VALIDATION_FAILED',
  CONFIG_MISSING_REQUIRED_FIELDS: 'CONFIG_MISSING_REQUIRED_FIELDS',

  DEPLOYMENT_NOT_FOUND: 'DEPLOYMENT_NOT_FOUND',
  DEPLOYMENT_ALREADY_RUNNING: 'DEPLOYMENT_ALREADY_RUNNING',
  DEPLOYMENT_NO_INFRA: 'DEPLOYMENT_NO_INFRA',
  DEPLOYMENT_IMAGE_NOT_FOUND: 'DEPLOYMENT_IMAGE_NOT_FOUND',
  DEPLOYMENT_HEALTH_CHECK_FAILED: 'DEPLOYMENT_HEALTH_CHECK_FAILED',
  DEPLOYMENT_TIMEOUT: 'DEPLOYMENT_TIMEOUT',

  PULUMI_EXECUTION_FAILED: 'PULUMI_EXECUTION_FAILED',
  PULUMI_STATE_CORRUPTED: 'PULUMI_STATE_CORRUPTED',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
} as const;

export type ErrorCodeType = (typeof ErrorCodes)[keyof typeof ErrorCodes];
